### ISSUE TITLE
Question: Where can I download 8.0.1?

### ISSUE THREAD

**Issue by SimonR-Nano** [wcxo/GitCracken#2]
Hello

I'm trying to get 8.3.0 but everytime I got this error:

```
(node:22496) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\s\Downloads\GitCracken-BoGnY\GitCracken-BoGnY\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\s\Downloads\GitCracken-BoGnY\GitCracken-BoGnY\dist\src\patcher.js:123
            throw new Error(`Can't patch ${patch.oldFileName}`);
```

Where can I download 8.0.1 please?

Thank you

**Comment by wangxuanjie** [comment]
> Hello
> 
> I'm trying to get 8.3.0 but everytime I got this error:
> 
> ```
> (node:22496) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\s\Downloads\GitCracken-BoGnY\GitCracken-BoGnY\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
> (Use `node --trace-deprecation ...` to show where the warning was created)
> C:\Users\s\Downloads\GitCracken-BoGnY\GitCracken-BoGnY\dist\src\patcher.js:123
>             throw new Error(`Can't patch ${patch.oldFileName}`);
> ```
> 
> Where can I download 8.0.1 please?
> 
> Thank you

Here is a link for 8.1.1 https://release.gitkraken.com/win64/GitKrakenSetup-8.1.1.exe
this repository is worked

**Comment by nolddor** [comment]
For Debian use:
https://release.axocdn.com/linux/GitKraken-v8.1.1.deb
